<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerjadinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [1, 'Emmy Suryandari, ST.MTM.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 1, 1, 1, 1, 1, 1],
            [2, 'Muhammad Taufiq, ST, MT', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 2, 2, 2, 2, 2, 2],
            [3, 'Achmad Taufik, S.T., M.T., M.S.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 3, 3, 3, 3, 3, 3],
            [4, 'Avia Enggar Tyasti, S.Si., M.A.B.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [5, 'Nanik Dyah Nurwani, S.E.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [6, 'Mamih', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [7, 'Erawan Kencana Saraharjo, ST.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [8, 'Jaya Rahmat, A.Md.Kom.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [9, 'Fernando Turnip', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [10, 'Fitriyanti, S.E.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [11, 'Rahmat Setiawan', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [12, 'Andrian Fahrizal, A.Md.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [13, 'Aditya Permana', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [14, 'Dani Saputra', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [15, 'Rahmat Dani', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [16, 'Linda Fitra Pertiwi', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [17, 'Muhammad Irfan', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [18, 'Fatchul Rahman Rusdin, S.TP', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [19, 'Benarifo Ahmada, S.Si', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [20, 'Setiyo Jatmiko, A.Md', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [21, 'Amirullah, S.AP', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [22, 'R. Yaman Sudrajat, S.E.I', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [23, 'Yudha Iskandar, ST', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [24, 'Muhammad Erya Sandy, A.P.Kb.N.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [25, 'Elvira Silviani Putri Siswoyo, ST., M.P', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [26, 'Eka Siti Khadijah, S.Sos', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [27, 'Yunika Lucianna Manihuruk, S.I.A.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [28, 'Andito Nugraha Candraningrat, A.Md.M.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [29, 'Pintaning Larasati, A.Md.Kb.N.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [30, 'Nurmaya Yulianti, SE, M.Han.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [31, 'Ade', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [32, 'Muhammad Hanif Abdurrahman', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [33, 'Aulia Rosalinda Baladika Jayanti, S.Kom', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [34, 'Muhamad Doni Munggaran, S.Kom.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [35, 'Bima Abhi Hussaen, S.Tr.I.Kom.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [36, 'Qorina Topazia, A.Md.A.B.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [37, 'Suzanne Agustin, MT', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [38, 'Evitriana Susanti Hatta, SS, M. Si', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [39, 'Margaretta Charolyna, SE, MM', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [40, 'Mila Zulfah, SE, M.SE.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [41, 'Rizalul Kalam, SE, M.SE', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [42, 'Aan Diana', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [43, 'Novi Puspitaningrum, S.Kom, M.SE', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [44, 'Hardi Budi Noviardi, S.Kom', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [45, 'Irma Rachmawati, S. Sos, M.Si', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [46, 'Eko Priyo Purnomo, S.S., M.Med.Kom.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [47, 'Fahmi Tanjung, S.T., M.Sc.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [48, 'Indah Arifiani, SE', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [49, 'Erwin Miftahudin, S.E., M.Sos.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [50, 'Agus Juniawan Khairi, S.T.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [51, 'Rizalina Yuni Riyanti, ST', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [52, 'Noveriya Husni Sanjaya, S.Ip., MPA', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [53, 'Yuni Afianti, S.Sos', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [54, 'Menik Noviyanti, S.I.A', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [55, 'Fitria Dwi Rahmadiah, S.IP', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [56, 'Lisbet, S.AP, M.P.M', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [57, 'Eva Andiana, ST', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [58, 'Dwi Septianingrum, A.Md.M.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [59, 'Varendra Kusuma Wardhana, S.M.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [60, 'Kadek Ade Prabhawati Dewi P., S.IP.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [61, 'Dhesa Ardhiyanta, S.Kom', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [62, 'Ulfah Safinatun Najah, A.Md.A.P.S.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [63, 'Muhammad Yunus Alim, S.A.P.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [64, 'Pri Hartina Fatimah, S.A.P', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [65, 'Widya Widayani, A. Md.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [66, 'Dani Puspasari, A.Md. A.Pkt.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [67, 'Sabrina Permata Alam, S.I.P.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [68, 'Karmila Peronika Sitanggang, S.E.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [69, 'Rida Rahmaningtyas, A.Md.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [70, 'Muhamad Jepri, S.T.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [71, 'Rizky Permana Putra, S.Kom', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [72, 'Kinanthi Hayuning Arundati, S.E.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [73, 'Shandita Pamesti Nur Annisa, S.T.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [74, 'Faiz Ardiyansah Nuurrahman, A.Md.Kom.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [75, 'Aprillia Ajeng Winastrie, A.Md.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [76, 'Danti Kamila Insani, S.T', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [77, 'Adibatul Isna, A.Md.Ak.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [78, 'Yuliana Puteri Handayani, S.T.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [79, 'Dian Syifaul Mufidah, S.T.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [80, 'Alexander Immanuel Simanungkalit, A.Md.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [81, 'Bintang Saqinna Putri, S.T.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [82, 'Dhelia Damayanty. S, A.P.Kb.N.', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [83, 'Martin Doloksaribu, ST, M.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [84, 'Yasinta Bunga Maharani', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [85, 'Annayla Dwindra Fakhira', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [86, 'Hermawan', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 1, 1, 1, 1, 1, 1],
            [87, 'Rosadi', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [88, 'Ricki Karuwianto', 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [89, 'Ir. Restu Yuni Widayati, MA', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [90, 'Andi Mukti Wibowo, SH', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [91, 'Hadiat Riswanda, S.Pi.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [92, 'Kusnadi', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [93, 'Monica Natasi Irawan, A.Md.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [94, 'Hendi Aryanta Tarigan, A.Md.Kb.N.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [95, 'Mohamad Rizki Primadhi, SE', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [96, 'Agustinus Cook Siallagan, SH', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [97, 'Istirani Agusti, S.Si', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [98, 'Asta Witama, ST', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [99, 'Pebri Handoyo, STP', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [100, 'Nur Fitriono, S.Pi', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [101, 'Dewi Tasari', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [102, 'Afifah Nurmaimanah, S.T.P.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [103, 'Vindilia Saka Mardha Ihsan Pratama, S.T', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [104, 'Erisa Maidona Ramadhany Putri, A.Md.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [105, 'Chordelia, ST, MSi', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [106, 'Lusiana Fitri, ST, MM', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [107, 'John Henry Sianipar, ST, MM', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [108, 'Antini Triwidati, SH, MH', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [109, 'Raja Andrie Agusvinus, ST', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [110, 'Yosi Trianggono, ST, MT, M.Sc', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [111, 'Hasan Fuadi, S.T., M.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [112, 'Vernando Arthur Zakarias, S.E.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [113, 'Adityo Murdiarto, S.T., M.T., M.Sc.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [114, 'Dewi Ayu Novita, ST', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [115, 'Rizal Priambudi, ST', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [116, 'Stephani Rizki Nugraheni, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [117, 'Alfiqie Tanjung, S.T', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [118, 'Hardio Arif, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [119, 'Al Hadid Pandu Setyawan, S.T', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [120, 'Ade Agil Saputra, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [121, 'Bachtiar Dhannu Artha, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [122, 'Nafis Setiabudi, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [123, 'Muin Farizal, S.T', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [124, 'Muhammad Kafi, S.T', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [125, 'Linda Savitri, S.H.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [126, 'Parlindungan Hotmatua Purba, ST.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [127, 'Fiqih Fandrian Pangestika, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [128, 'Mida Rahayu, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [129, 'Muhammad Ichsan Yozianto, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [130, 'Arham Rizqy Athallah, S.T', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [131, 'Avian Lukman Setya Budi, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [132, 'Raihan Naufal Nirwana, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [133, 'Dzaky Ahmad Fertoni, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [134, 'Andhika Almas Farid, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [135, 'Rifqi Muhammad Awaluddin, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [136, 'Ulfah Fuadi, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [137, 'Muhammad Rasyid, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [138, 'Nadya Syafa Kamila, S.T.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [139, 'Saktiadi Catur Permana, S.Ak.', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [140, 'Arizando Martin Nasution', 'Pusat Pengawasan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [141, 'Singgih Oktavian, S.T.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [142, 'E. Setiorini Dwi Palupi, S.Pd.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [143, 'Apt. Ade Hikmawati, S.Farm.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [144, 'Erika Nandiya, S.Pd.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [145, 'Syarifa Arum Kusumastuti, ST, M.A.I.E.,', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [146, 'Muchdopir, ST', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [147, 'Azhar Arnata, S. Farm', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [148, 'Yudi Setianto, A.Md', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [149, 'Mutiara Febriyana Bethasyani, S.Tr.Si', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [150, 'Singgih Oktavian, ST', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [151, 'Mukhammad Sena Suratman, S.Tr.T', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [152, 'Marlisa, S.Tr.T.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [153, 'Zakiyah Antarisca', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [154, 'Ladiman', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [155, 'Endang Suherlan Rohman', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [156, 'Noor Fadlilah, A.Md', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [157, 'Alifah Hana Fikriyah, A.P.Kb.N.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [158, 'Dr. Ir. Sudarto, MM', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [159, 'Dr. Suharman, SP., M.Si', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [160, 'Welldian Saragih, S.Kom, MMSI', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [161, 'Isti Kartika, S.Ds', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [162, 'Surya Akbar Wijaya, ST, M.S.E', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [163, 'Medino Dian Putra, SH.MH', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [164, 'Manda Pratomo, S.T., I.P.M., M.S.E', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [165, 'Dwi Yulianto, S.Si, M.Ec.Dev', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [166, 'Moko Nugroho, S.T., M.S.E', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [167, 'Afrizal Amir, S.T., M.T., M.Sc.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [168, 'Sonya Hitipeuw', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [169, 'Firmansyah, S.T., M.E.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [170, 'Muhammad Wisnu Muq`Asfa, ST', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [171, 'Wishnu Raynar, S.T.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [172, 'Fariz Rizki Darmawan, S.I.A.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [173, 'Rizquna Ramadhani, S.AP.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [174, 'Devina Inayah Iryani, S.T.', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [175, 'Silfany Abidin', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [176, 'Syammas Hansfriyadi', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [177, 'Monica Inda Sari', 'Pusat Optimalisasi Pemanfaatan Teknologi Industri dan Kebijakan Jasa Industri', 0, 0, 0, 0, 0, 0],
            [178, 'Dr. Ir. Tri Ligayanti, S.T., M.Si.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [179, 'Lukman Jamil, S.ST.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [180, 'Adhi Christian Brahmantyo, S.Kom.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [181, 'Murita', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [182, 'Daaniyal Ahmad Santosa, S.T.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [183, 'Yeni Amelia, S.M.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [184, 'Dzatalin Alveiny Ash Shafikh, A.P.Kb.N', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [185, 'Gerliv Rajagukguk, ST', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [186, 'Sutarto, ST.MT', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [187, 'Eko Hari Purnomo, S.Kom, MT', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [188, 'Adrian Adityo, S.T, M.Eng', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [189, 'Agus Kurniawan, S.T, M.SE', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [190, 'Aries Kuswidianto, ST, M.S.E', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [191, 'Andri Tricahyo, ST', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [192, 'David Hendra Gunawan, SH', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [193, 'Ari Uliana, ST, MT', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [194, 'Risetio Canggih Dwiputra, S.T.P., M.Ec', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [195, 'Naili Sofiyaningsih, ST., M.Si', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [196, 'Sumarni, S.T., M.T., M.S.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [197, 'Risdianto, S.T', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [198, 'Lukman Jamil, S.ST', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [199, 'Yoseinaita Br Pelawi, ST', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [200, 'Miranti Rahayu, S.T.P., M.E.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [201, 'Andreas Kristianto, S.T., M.P.A., M.A.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [202, 'Raeshifa Diani Almy, S.T.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [203, 'Lita Rahma Pristina, S.Tr.T.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [204, 'Hendrik Iswanto', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [205, 'Ester Ayu C. Siagian', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [206, 'Arsandi Yusuf, S.T.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [207, 'Akhwani, S.H.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [208, 'Sisca Dwi Anggraini, S.H.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [209, 'Miftah Hulhadi, S.E', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [210, 'Leni Anggraini, S.T.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [211, 'Dena Trysa Aulia, S.H.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [212, 'Iqrammil Kubra Asweril, S.T', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [213, 'Cindy Octavia Dwi Nugraha, S.A.P.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [214, 'Devina Rahmadyanthi Suhendri, S.T', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [215, 'Arya Yudistira, S.T., M.T.', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [216, 'Muhammad Syaeful Haq Rabbani', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [217, 'Muhammad Nur', 'Pusat Perumusan, Penerapan, dan Pemberlakuan Standardisasi Industri', 0, 0, 0, 0, 0, 0],
            [218, 'Apit Pria Nugraha, ST, MPP', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [219, 'Hapsari Pradana Iswari, SH', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [220, 'Diah Ayu Kusuma, S.E', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [221, 'Diba Adawiah Azka, A.md', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [222, 'Rizka Tri Wardhani, ST', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [223, 'Evtriyandani, S.T., M.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [224, 'Ricko Immanuel Wicaksana, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [225, 'Muhammad Abdul Aziz Ramdhani, S.Si', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [226, 'Atika Budiana, S.E.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [227, 'Fausan Arif Darmadi, S.T', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [228, 'Undung Permatasari, S.E.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [229, 'Kumaya Aikathun Nu\'Ma, S.Tr.T', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [230, 'Emmy Doris Hutauruk, A.Md', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [231, 'Muchammad Pudjianto, S.E, M.M', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [232, 'Ratna Puspita, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [233, 'Ilham Anhar Chalid, A.P.Kb.N.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [234, 'Rr. Sri Gadis Pari Bekti, S.Si, M.Si.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [235, 'Dr. Andriati Cahyaningsih, S.Si,M.Si', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [236, 'Astika Andhini, S.Si, M.SE.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [237, 'Andalia Gustari, ST', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [238, 'Achmad Taufik, ST, MT, MS.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [239, 'Dena Sismaraini, S.T., M.Si', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [240, 'Evy Aprina Tambunan', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [241, 'Sylvia Diah Ayu Kusumawardani, S.T., M.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [242, 'Zakiyah Ash-Shofi, S.T., M.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [243, 'Istifari Azizah', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [244, 'Wilda Sania Mukti', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [245, 'Harry Dwika Putra, S.Kom.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [246, 'Sindu Andita Pratama, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [247, 'Vini Jayanti, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [248, 'Muhammad Tasyriq, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [249, 'Fadil Latifuddin, S.Ling', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [250, 'Anugerah Arif Akbar, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [251, 'Agnes Anggita, S.T.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [252, 'Mikalisa Aryani, S.T', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [253, 'Timothy Jeffrey Walter, S.Ling.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [254, 'Andini Indar Putri, S.Biotek.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [255, 'Kirana Nurul Arifiani, S.Ling.', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [256, 'Quinnike Aisy Maskurin, S. Biotek', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [257, 'Siti Aisyah', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [258, 'Princessa Ridhianty', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
            [259, 'Suhenda', 'Pusat Industri Hijau', 0, 0, 0, 0, 0, 0],
        ];

        foreach ($data as $row) {
            DB::table('perjadin')->insert([
                'no'           => $row[0],
                'nama'         => $row[1],
                'unit_kerja'   => $row[2],
                'sppd_dn'      => $row[3],
                'sppd_dk'      => $row[4],
                'sppd_dln'     => $row[5],
                'hari_dn'      => $row[6],
                'hari_dk'      => $row[7],
                'hari_dln'     => $row[8],
            ]);
        }
    }
}
